import { Controller, Get, Param, ParseUUIDPipe, Query } from "@nestjs/common";
import { Throttle } from "@nestjs/throttler";
import { CurrentActor, RequireRoles } from "../common/auth/auth.decorators";
import type { Actor } from "../common/auth/actor";
import { rmClient, rmClientWhere } from "../common/auth/rm-client";
import { PrismaService } from "../database/prisma.service";
import { MisQueryDto } from "./client-reports.controller";
import { ClientReportsService } from "./client-reports.service";

/**
 * The RM's companies and their MIS: the same preset MIS the Company Admin gets,
 * generated by the RM for a company assigned to it. Exports are audited.
 */
@Controller("rm/clients")
@RequireRoles("SPOC_RM", "OPS_MANAGER", "PLATFORM_ADMIN")
export class RmClientMisController {
  constructor(
    private readonly prisma: PrismaService,
    private readonly reports: ClientReportsService,
  ) {}

  @Get()
  async clients(@CurrentActor() actor: Actor) {
    const rows = await this.prisma.client.findMany({
      where: rmClientWhere(actor),
      orderBy: { displayName: "asc" },
      take: 500,
      select: { publicId: true, displayName: true },
    });
    return {
      items: rows.map((row) => ({ id: row.publicId, name: row.displayName })),
    };
  }

  @Get(":clientId/mis")
  async mis(
    @CurrentActor() actor: Actor,
    @Param("clientId", ParseUUIDPipe) clientId: string,
    @Query() query: MisQueryDto,
  ) {
    const company = await rmClient(this.prisma, actor, clientId);
    return {
      company: { id: company.publicId, name: company.displayName },
      ...(await this.reports.mis(
        actor,
        query.preset,
        query.from,
        query.to,
        company,
      )),
    };
  }

  @Get(":clientId/mis/export")
  @Throttle({ default: { limit: 20, ttl: 60_000 } })
  async misExport(
    @CurrentActor() actor: Actor,
    @Param("clientId", ParseUUIDPipe) clientId: string,
    @Query() query: MisQueryDto,
  ) {
    const company = await rmClient(this.prisma, actor, clientId);
    return this.reports.misExport(
      actor,
      query.preset,
      query.from,
      query.to,
      company,
    );
  }
}
