export const Permission = {
  DashboardRead: "dashboard:read",
  ClientRead: "client:read",
  ClientWrite: "client:write",
  CaseRead: "case:read",
  CaseCreate: "case:create",
  CaseTransition: "case:transition",
  ConsentManage: "consent:manage",
  DocumentRead: "document:read",
  DocumentWrite: "document:write",
  TaskRead: "task:read",
  TaskWrite: "task:write",
  ClarificationRead: "clarification:read",
  ClarificationWrite: "clarification:write",
  QaReview: "qa:review",
  ReportRead: "report:read",
  ReportGenerate: "report:generate",
  FieldVisitRead: "field-visit:read",
  FieldVisitWrite: "field-visit:write",
  FieldEvidenceRead: "field-evidence:read",
  AuditRead: "audit:read",
  SettingsManage: "settings:manage",
  CrmRead: "crm:read",
  CrmWrite: "crm:write",
  FinanceRead: "finance:read",
  FinanceWrite: "finance:write",
  UserRead: "user:read",
  UserWrite: "user:write",
  NotificationRead: "notification:read",
} as const;

export type PermissionName = (typeof Permission)[keyof typeof Permission];
