export const PERMISSIONS = [
  "dashboard:read",
  "case:read",
  "case:create",
  "case:assign",
  "case:transition",
  "case:escalate",
  "clarification:manage",
  "exception:manage",
  "sla:read",
  "team:read",
  "client:read",
  "client:write",
  "user:read",
  "user:write",
  "settings:manage",
  "audit:read",
  "report:read",
  "finance:read",
  "crm:read",
  "crm:write",
  "crm:assign",
  "crm:forecast",
  "crm:export",
  "notification:read",
  "qa:read",
  "field:read",
  "field:manage",
  "security:manage",
] as const;

export type Permission = (typeof PERMISSIONS)[number];

export const PERMISSION_LABELS: Record<Permission, string> = {
  "dashboard:read": "View operational dashboards",
  "case:read": "View verification cases",
  "case:create": "Create verification cases",
  "case:assign": "Assign cases to verifiers",
  "case:transition": "Move cases between delivery stages",
  "case:escalate": "Escalate cases to clients",
  "clarification:manage": "Raise and resolve clarifications",
  "exception:manage": "Own and resolve exceptions",
  "sla:read": "View SLA performance analytics",
  "team:read": "View verifier capacity and workload",
  "client:read": "View client organisations",
  "client:write": "Create and edit clients",
  "user:read": "View user IDs and access",
  "user:write": "Create, suspend and reset user IDs",
  "settings:manage": "Manage platform settings",
  "audit:read": "Read the immutable audit trail",
  "report:read": "View and download reports",
  "finance:read": "View invoices and payments",
  "crm:read": "View CRM pipeline and opportunities",
  "crm:write": "Create and edit opportunities and activities",
  "crm:assign": "Assign sales owners and rebalance the pipeline",
  "crm:forecast": "View revenue forecast and targets",
  "crm:export": "Export CRM pipeline data",
  "notification:read": "Read workspace notifications",
  "qa:read": "Access QA review queues",
  "field:read": "Access field operations",
  "field:manage": "Schedule visits and clear field exceptions",
  "security:manage": "Manage account security and sessions",
};
