export const CheckTypes = [
  "IDENTITY",
  "ADDRESS",
  "EMPLOYMENT",
  "EDUCATION",
  "CRIMINAL",
  "COURT_RECORD",
  "REFERENCE",
  "GLOBAL_DATABASE",
  "DRUG_TEST",
] as const;

export const CaseStatuses = [
  "DRAFT",
  "CONSENT_PENDING",
  "DOCUMENT_PENDING",
  "IN_PROGRESS",
  "CLARIFICATION_PENDING",
  "QA_REVIEW",
  "COMPLETED",
  "CLOSED",
  "CANCELLED",
] as const;

export const caseTransitions: Record<string, readonly string[]> = {
  DRAFT: ["CONSENT_PENDING", "CANCELLED"],
  CONSENT_PENDING: ["DOCUMENT_PENDING", "CANCELLED"],
  DOCUMENT_PENDING: ["IN_PROGRESS", "CLARIFICATION_PENDING", "CANCELLED"],
  IN_PROGRESS: ["CLARIFICATION_PENDING", "QA_REVIEW", "CANCELLED"],
  CLARIFICATION_PENDING: ["IN_PROGRESS", "CANCELLED"],
  QA_REVIEW: ["IN_PROGRESS", "COMPLETED"],
  COMPLETED: ["CLOSED"],
  CLOSED: [],
  CANCELLED: [],
};
