/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as ClientPortalRouteImport } from './routes/client-portal'
import { Route as ExceptionsRouteImport } from './routes/exceptions'
import { Route as ExecutiveRouteImport } from './routes/executive'
import { Route as FieldExecutiveRouteImport } from './routes/field-executive'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as LoginRouteImport } from './routes/login'
import { Route as QaReviewRouteImport } from './routes/qa-review'
import { Route as SalesCrmRouteImport } from './routes/sales-crm'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifierRouteImport } from './routes/verifier'
import { Route as CandidateAccessIdRouteImport } from './routes/candidate.$accessId'
import { Route as CasesCaseIdRouteImport } from './routes/cases.$caseId'
import { Route as ClarificationClarificationIdRouteImport } from './routes/clarification.$clarificationId'
import { Route as ConsentConsentIdRouteImport } from './routes/consent.$consentId'
import { Route as ReportsVerifyAuthenticityCodeRouteImport } from './routes/reports.verify.$authenticityCode'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientPortalRoute = ClientPortalRouteImport.update({
  id: '/client-portal',
  path: '/client-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const ExceptionsRoute = ExceptionsRouteImport.update({
  id: '/exceptions',
  path: '/exceptions',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutiveRoute = ExecutiveRouteImport.update({
  id: '/executive',
  path: '/executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FieldExecutiveRoute = FieldExecutiveRouteImport.update({
  id: '/field-executive',
  path: '/field-executive',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const QaReviewRoute = QaReviewRouteImport.update({
  id: '/qa-review',
  path: '/qa-review',
  getParentRoute: () => rootRouteImport,
} as any)
const SalesCrmRoute = SalesCrmRouteImport.update({
  id: '/sales-crm',
  path: '/sales-crm',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifierRoute = VerifierRouteImport.update({
  id: '/verifier',
  path: '/verifier',
  getParentRoute: () => rootRouteImport,
} as any)
const CandidateAccessIdRoute = CandidateAccessIdRouteImport.update({
  id: '/candidate/$accessId',
  path: '/candidate/$accessId',
  getParentRoute: () => rootRouteImport,
} as any)
const CasesCaseIdRoute = CasesCaseIdRouteImport.update({
  id: '/cases/$caseId',
  path: '/cases/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClarificationClarificationIdRoute =
  ClarificationClarificationIdRouteImport.update({
    id: '/clarification/$clarificationId',
    path: '/clarification/$clarificationId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ConsentConsentIdRoute = ConsentConsentIdRouteImport.update({
  id: '/consent/$consentId',
  path: '/consent/$consentId',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsVerifyAuthenticityCodeRoute =
  ReportsVerifyAuthenticityCodeRouteImport.update({
    id: '/reports/verify/$authenticityCode',
    path: '/reports/verify/$authenticityCode',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/client-portal': typeof ClientPortalRoute
  '/exceptions': typeof ExceptionsRoute
  '/executive': typeof ExecutiveRoute
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/qa-review': typeof QaReviewRoute
  '/sales-crm': typeof SalesCrmRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/verifier': typeof VerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/client-portal': typeof ClientPortalRoute
  '/exceptions': typeof ExceptionsRoute
  '/executive': typeof ExecutiveRoute
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/qa-review': typeof QaReviewRoute
  '/sales-crm': typeof SalesCrmRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/verifier': typeof VerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/change-password': typeof ChangePasswordRoute
  '/client-portal': typeof ClientPortalRoute
  '/exceptions': typeof ExceptionsRoute
  '/executive': typeof ExecutiveRoute
  '/field-executive': typeof FieldExecutiveRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/qa-review': typeof QaReviewRoute
  '/sales-crm': typeof SalesCrmRoute
  '/security': typeof SecurityRoute
  '/settings': typeof SettingsRoute
  '/verifier': typeof VerifierRoute
  '/candidate/$accessId': typeof CandidateAccessIdRoute
  '/cases/$caseId': typeof CasesCaseIdRoute
  '/clarification/$clarificationId': typeof ClarificationClarificationIdRoute
  '/consent/$consentId': typeof ConsentConsentIdRoute
  '/reports/verify/$authenticityCode': typeof ReportsVerifyAuthenticityCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/change-password'
    | '/client-portal'
    | '/exceptions'
    | '/executive'
    | '/field-executive'
    | '/finance'
    | '/login'
    | '/qa-review'
    | '/sales-crm'
    | '/security'
    | '/settings'
    | '/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/consent/$consentId'
    | '/reports/verify/$authenticityCode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/change-password'
    | '/client-portal'
    | '/exceptions'
    | '/executive'
    | '/field-executive'
    | '/finance'
    | '/login'
    | '/qa-review'
    | '/sales-crm'
    | '/security'
    | '/settings'
    | '/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/consent/$consentId'
    | '/reports/verify/$authenticityCode'
  id:
    | '__root__'
    | '/'
    | '/change-password'
    | '/client-portal'
    | '/exceptions'
    | '/executive'
    | '/field-executive'
    | '/finance'
    | '/login'
    | '/qa-review'
    | '/sales-crm'
    | '/security'
    | '/settings'
    | '/verifier'
    | '/candidate/$accessId'
    | '/cases/$caseId'
    | '/clarification/$clarificationId'
    | '/consent/$consentId'
    | '/reports/verify/$authenticityCode'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
  ClientPortalRoute: typeof ClientPortalRoute
  ExceptionsRoute: typeof ExceptionsRoute
  ExecutiveRoute: typeof ExecutiveRoute
  FieldExecutiveRoute: typeof FieldExecutiveRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  QaReviewRoute: typeof QaReviewRoute
  SalesCrmRoute: typeof SalesCrmRoute
  SecurityRoute: typeof SecurityRoute
  SettingsRoute: typeof SettingsRoute
  VerifierRoute: typeof VerifierRoute
  CandidateAccessIdRoute: typeof CandidateAccessIdRoute
  CasesCaseIdRoute: typeof CasesCaseIdRoute
  ClarificationClarificationIdRoute: typeof ClarificationClarificationIdRoute
  ConsentConsentIdRoute: typeof ConsentConsentIdRoute
  ReportsVerifyAuthenticityCodeRoute: typeof ReportsVerifyAuthenticityCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client-portal': {
      id: '/client-portal'
      path: '/client-portal'
      fullPath: '/client-portal'
      preLoaderRoute: typeof ClientPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exceptions': {
      id: '/exceptions'
      path: '/exceptions'
      fullPath: '/exceptions'
      preLoaderRoute: typeof ExceptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/executive': {
      id: '/executive'
      path: '/executive'
      fullPath: '/executive'
      preLoaderRoute: typeof ExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/field-executive': {
      id: '/field-executive'
      path: '/field-executive'
      fullPath: '/field-executive'
      preLoaderRoute: typeof FieldExecutiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/qa-review': {
      id: '/qa-review'
      path: '/qa-review'
      fullPath: '/qa-review'
      preLoaderRoute: typeof QaReviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sales-crm': {
      id: '/sales-crm'
      path: '/sales-crm'
      fullPath: '/sales-crm'
      preLoaderRoute: typeof SalesCrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verifier': {
      id: '/verifier'
      path: '/verifier'
      fullPath: '/verifier'
      preLoaderRoute: typeof VerifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/candidate/$accessId': {
      id: '/candidate/$accessId'
      path: '/candidate/$accessId'
      fullPath: '/candidate/$accessId'
      preLoaderRoute: typeof CandidateAccessIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cases/$caseId': {
      id: '/cases/$caseId'
      path: '/cases/$caseId'
      fullPath: '/cases/$caseId'
      preLoaderRoute: typeof CasesCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clarification/$clarificationId': {
      id: '/clarification/$clarificationId'
      path: '/clarification/$clarificationId'
      fullPath: '/clarification/$clarificationId'
      preLoaderRoute: typeof ClarificationClarificationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consent/$consentId': {
      id: '/consent/$consentId'
      path: '/consent/$consentId'
      fullPath: '/consent/$consentId'
      preLoaderRoute: typeof ConsentConsentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports/verify/$authenticityCode': {
      id: '/reports/verify/$authenticityCode'
      path: '/reports/verify/$authenticityCode'
      fullPath: '/reports/verify/$authenticityCode'
      preLoaderRoute: typeof ReportsVerifyAuthenticityCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangePasswordRoute: ChangePasswordRoute,
  ClientPortalRoute: ClientPortalRoute,
  ExceptionsRoute: ExceptionsRoute,
  ExecutiveRoute: ExecutiveRoute,
  FieldExecutiveRoute: FieldExecutiveRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  QaReviewRoute: QaReviewRoute,
  SalesCrmRoute: SalesCrmRoute,
  SecurityRoute: SecurityRoute,
  SettingsRoute: SettingsRoute,
  VerifierRoute: VerifierRoute,
  CandidateAccessIdRoute: CandidateAccessIdRoute,
  CasesCaseIdRoute: CasesCaseIdRoute,
  ClarificationClarificationIdRoute: ClarificationClarificationIdRoute,
  ConsentConsentIdRoute: ConsentConsentIdRoute,
  ReportsVerifyAuthenticityCodeRoute: ReportsVerifyAuthenticityCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
